<a href="https://colab.research.google.com/github/ravi-kr/pytorch-practice/blob/master/1_Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
torch.__version__

'1.5.1+cu101'

In [4]:
import numpy as np

In [5]:
lst = [3, 4, 5, 6]
arr = np.array(lst)

In [6]:
arr

array([3, 4, 5, 6])

In [7]:
arr.dtype

dtype('int64')

### Creating Numpy array to Pytorch tensors

In [9]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [10]:
tensors[2]

tensor(5)

In [11]:
tensors.dtype

torch.int64

In [12]:
tensors[1:4]

tensor([4, 5, 6])

In [13]:
tensors[3] = 100

In [14]:
tensors

tensor([  3,   4,   5, 100])

In [15]:
arr

array([  3,   4,   5, 100])

In [17]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [19]:
tensor_arr[3] = 120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120])
[  3   4   5 100]


In [21]:
torch.zeros(2,3, dtype = torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [22]:
torch.ones(2,3, dtype = torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [23]:
a = torch.tensor(np.arange(0,15).reshape(5,3))

In [25]:
a[:,0:3]

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

#### Arithmetic Operations

In [30]:
a = torch.tensor([3,4,5], dtype = torch.float)
b = torch.tensor([4,5,6], dtype = torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [31]:
torch.add(a, b)

tensor([ 7.,  9., 11.])

In [32]:
c = torch.zeros(3)
c

tensor([0., 0., 0.])

In [33]:
torch.add(a,b, out = c)

tensor([ 7.,  9., 11.])

In [34]:
c

tensor([ 7.,  9., 11.])

In [35]:
a = torch.tensor([3,4,5], dtype = torch.float)
b = torch.tensor([4,5,6], dtype = torch.float)

In [36]:
torch.add(a, b).sum()

tensor(27.)

In [37]:
x = torch.tensor([3,4,5], dtype = torch.float)
y = torch.tensor([4,5,6], dtype = torch.float)

In [38]:
print(x)
print(y)

tensor([3., 4., 5.])
tensor([4., 5., 6.])


In [39]:
x.mul(y)

tensor([12., 20., 30.])

In [40]:
x.dot(y)

tensor(62.)

In [42]:
x = torch.tensor([[1,4,2], [1,5,5]], dtype = torch.float)
y = torch.tensor([[5,7], [8,6], [9,11]], dtype = torch.float)
print(x)
print(y)

tensor([[1., 4., 2.],
        [1., 5., 5.]])
tensor([[ 5.,  7.],
        [ 8.,  6.],
        [ 9., 11.]])


In [43]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [44]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [45]:
x@y

tensor([[55., 53.],
        [90., 92.]])

#### Backpropogation using Pytorch

In [46]:
x = torch.tensor(4.0, requires_grad=True)

In [47]:
x

tensor(4., requires_grad=True)

In [48]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [49]:
y.backward()
y

tensor(16., grad_fn=<PowBackward0>)

In [50]:
print(x.grad)

tensor(8.)


In [51]:
lst = [[2.,3.,1.], [4.,5.,3.], [7.,6.,4.]]
torch_input = torch.tensor(lst, requires_grad = True)

In [52]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [53]:
y = torch_input**3 + torch_input**2

In [54]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [55]:
z = y.sum()

In [56]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [57]:
z.backward()

In [58]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [59]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])